// @vitest-environment node
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import icons from '../assets/pwa-icons.json'

/* eslint-disable security/detect-non-literal-fs-filename -- paths are this repository's own public/ files, from the committed icon index */

/**
 * The static half of the installable app: files generated by
 * scripts/pwa-icons.mjs or written by hand, which no build step checks.
 */
const PUBLIC = join(import.meta.dirname, '../public')

/** Width and height from a PNG's IHDR chunk. */
function pngSize(file: string) {
  const png = readFileSync(file)
  return { width: png.readUInt32BE(16), height: png.readUInt32BE(20) }
}

describe('home-screen icons', () => {
  it.each(Object.entries(icons))('%s exists at its hashed URL in its size', (_, icon) => {
    expect(icon.src).toMatch(/^\/pwa\/[a-z-]+-?\d*\.[0-9a-f]{8}\.png$/)
    const file = join(PUBLIC, icon.src)
    expect(existsSync(file)).toBe(true)
    expect(pngSize(file)).toStrictEqual({ width: icon.size, height: icon.size })
  })

  it('has the sizes the manifest and iOS ask for', () => {
    expect(Object.values(icons).map((icon) => icon.size)).toStrictEqual([192, 512, 180])
  })
})

describe('offline page', () => {
  const html = readFileSync(join(PUBLIC, 'offline.html'), 'utf8')

  it('says what happened, in German', () => {
    expect(html).toContain('<html lang="de">')
    expect(html).toContain('Du bist offline')
  })

  it('shows the current icon — the one that is precached with it', () => {
    expect(html).toContain(`src="${icons['icon-192'].src}"`)
  })

  it('loads nothing else: offline, any other request would fail', () => {
    const references = [...html.matchAll(/\b(?:src|href)="([^"]+)"/g)].map((match) => match[1])
    expect(references).toStrictEqual([icons['icon-192'].src])
    expect(html).not.toMatch(/https?:\/\//)
  })
})

/* eslint-enable security/detect-non-literal-fs-filename */
