name: "frontend:test:build test code"

on: push

jobs:
  # only (but most important) job from this workflow required for pull requests
  # check results serve as run conditions for all other jobs here
  files-changed:
    name: Detect File Changes - frontend-test-build-code
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.filter }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.1.7

      - name: Check for frontend file changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            filter:
              - 'frontend/**/*'
              - '.github/workflows/*'
          list-files: shell

  build:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: frontend/.tool-versions

      - name: Env File
        run: cp .env.example .env
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Frontend | Build
        run: npm ci && npm run build
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Frontend | Size Check
        run: npm run test:size
        working-directory: ${{env.WORKING_DIRECTORY}}